name: Nightly

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build (per OS)
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            npm run build:win
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            npm run build:mac
          else
            npm run build:linux
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-nightly
          path: |
            dist/**/*.exe
            dist/**/*.dmg
            dist/**/*.zip
            dist/**/*.AppImage
            dist/**/*.deb
          if-no-files-found: error

  release-nightly:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Compute tag/title
        id: meta
        run: |
          SHA_SHORT=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "tag=nightly-${SHA_SHORT}" >> $GITHUB_OUTPUT
          echo "name=Nightly ${SHA_SHORT}" >> $GITHUB_OUTPUT

      - name: Create/Update prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          prerelease: true
          draft: false
          generate_release_notes: true
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
